### ISSUE TITLE
starting Httplistner and httpslistner service

### ISSUE THREAD

**Issue by shreyaskulkarni412** [dnif/DigiVigi#10]
Hello,

For do certain things in dnif. I want to start http and https service. So anyone any idea for how to start this service?

**Comment by PRASHANT-SAWANT** [comment]
Hey Shreyas,
Good thing you asked. I just figured these services need to be started inside DNIF container.
And to do so, you will have to do a SSH to DNIF Container (refer this DNIF Docs Page to do so: https://dnif.it/docs/guides/tutorials/access-dnif-container-via-ssh.html)

Once inside the container, run the following commands in sequence.
**1st Command:**
$ supervisorctl
O/P: All services along with their statuses will be displayed
**2nd Command:** (now this depends on which listener service you want to use)
$ start httplistener
OR
$ start httpslistener 

P.S:
Usually this service is required for listening to HTTP Post requests coming from client.
