### ISSUE TITLE
SMTP Configuration issue 

### ISSUE THREAD

**Issue by shreyaskulkarni412** [dnif/DigiVigi#15]
I can not configure the SMTP on my machine is there specific steps for it

**Comment by PRASHANT-SAWANT** [comment]
Hey @shreyaskulkarni412 ,

The DNIF website documentation already assumes you might have a SMTP server of your own or that you are aware of one, with proper credentials which are needed for authentication purposes.

There's a **SMTP Config Guide** I have uploaded under the **Guiding_Documents** folder. Follow the steps to configure and run the SMTP feature in  your DNIF instance.
