### ISSUE TITLE
DNIF installation on MAC 

### ISSUE THREAD

**Issue by shreyaskulkarni412** [dnif/DigiVigi#5]
I have installed docker on mac machine. Then I execute "sudo docker-compose up" command. It shows me the ASCII of DNIF which is a sign of completion of the DNIF installation. But after that when I tried to connect with the source IP on [https://go.dnif.it/] . It is not connecting. But in case of Ubuntu machine, it works fine   

Is there any specific issue for mac machine?

**Comment by PRASHANT-SAWANT** [comment]
Hey Shreyas, no idea on that though. I usually work on Windows or Linux OS's

You should try posting this query on their google forum here: https://groups.google.com/forum/#!forum/dnifhq

If you do find something on this issue, do post it here.

**Comment by shreyaskulkarni412** [comment]
I think for DNIF installation port 826 want to be open. But in mac machine port 826 is closed so It gives the problem for the installation.

**Comment by PRASHANT-SAWANT** [comment]
So did it fix the problem?

**Comment by PRASHANT-SAWANT** [comment]
@shreyaskulkarni412 

Did you find a solution to this issue?

**Comment by shreyaskulkarni412** [comment]
@PRASHANT-SAWANT 

Actually, I tried to open that port in mac but can not do. So I started installation on the ubuntu.
